.catalog:
  name: "Custom-Gogs"
  version: "custom-v0.0.1"
  description: |
    A painless self-hosted Git service.
  uuid: gogs-0
  minimum_rancher_version: v1.1.0
  questions:
    - variable: public_port
      description: "public port to access the mysql server"
      label: "Public Port"
      required: true
      default: "3306"
      type: "int"
    - variable: http_port
      description: "http port to access gogs webui"
      label: "Http Port"
      required: true
      default: "10080" 
      type: "int"
    - variable: ssh_port
      description: "ssh port to access gogs cli"
      label: "SSH Port"
      required: true
      default: "222"
      type: "int"
    - variable: mysql_password
      description: "mysql root password"
      label: "Mysql Password"
      required: true
      default: ""
      type: "password"

gogs:
